version: '3'

services:

  front:
    build:
      dockerfile: ./front/Dockerfile
    volumes:
        - ./front:/src
    command: sh -c "cd app && PORT=3000 yarn start"
    ports:
      - "3000:3000"